# Generated by Django 5.2.12 on 2026-05-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
        ('facturation', '0006_alter_facture_statut_alter_factureproforma_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_depense', models.CharField(editable=False, max_length=50, unique=True)),
                ('type_depense', models.CharField(choices=[('RETOUR_CLIENT', 'Remboursement client (retour vente)'), ('CHARGE_OPERATIONNELLE', 'Charge opérationnelle'), ('FOURNITURES', 'Fournitures & consommables'), ('TRANSPORT', 'Transport & livraison'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_echange', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='entreprise.pointvente')),
                ('retour_vente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depense_liee', to='facturation.retourvente')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
