# Generated by Django 5.2.12 on 2026-05-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icone', models.CharField(blank=True, default='ti-cash', help_text='Classe Tabler Icons, ex : ti-truck', max_length=60)),
                ('couleur', models.CharField(blank=True, default='#4c6ef5', help_text='Couleur hex, ex : #e65100', max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_systeme', models.BooleanField(default=False, help_text='Type créé automatiquement, non supprimable.')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_depense', to='entreprise.entreprise')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
                'unique_together': {('entreprise', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='depenses.typedepense'),
        ),
    ]
