# Generated by Django 4.0 on 2026-03-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0002_profil_profil_id'),
        ('entreprise', '0002_fournisseur_produit_methode_gestion_produit_vie_and_more'),
        ('achat', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=20)),
                ('date_inventaire', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.depot')),
                ('pointdevente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.pointvente')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_reelle', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockdepot', to='entreprise.depot')),
                ('pointdevente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockpoint', to='entreprise.pointvente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_stock', to='entreprise.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recu', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantite_affectee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantite_ecartee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantite_active', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dateproduction', models.DateField(blank=True, null=True)),
                ('dateexpiration', models.DateField(blank=True, null=True)),
                ('lot_batch', models.CharField(max_length=20)),
                ('unite', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.depot')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.profil')),
                ('ligneordreachat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achat.ligneordreachat')),
                ('pointvente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.pointvente')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantite_physique', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ecart', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.produit')),
            ],
        ),
    ]
