# Generated by Django 5.2.12 on 2026-04-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0018_alter_pointvente_code_pointvente'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='location_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.location'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='lot_batch',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='unite',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pointdevente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockpoint', to='entreprise.pointvente'),
        ),
    ]
