# Generated by Django 5.2.12 on 2026-05-01 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0025_produit_entreprise_sku_unique'),
        ('stock', '0005_stock_plan_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMiseAEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motif', models.TextField(verbose_name='Motif / raison')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                (
                    'cree_par',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.depot')),
                (
                    'pointdevente',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='entreprise.pointvente',
                    ),
                ),
                (
                    'produit',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stock_mises_a_ecart',
                        to='entreprise.produit',
                    ),
                ),
            ],
            options={
                'verbose_name': "Mise à l'écart stock",
                'verbose_name_plural': "Mises à l'écart stock",
                'indexes': [
                    models.Index(fields=['produit', 'depot', 'pointdevente', 'actif'], name='stock_stock_produit_ff5ee6_idx')
                ],
            },
        ),
    ]
