# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0025_produit_entreprise_sku_unique'),
        ('stock', '0006_stock_mise_a_ecart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonAjustementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'numero',
                    models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name="Numéro d'ajustement"),
                ),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                (
                    'cree_par',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bons_ajustement_crees',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'depot',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='entreprise.depot',
                    ),
                ),
                (
                    'entreprise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bons_ajustement_stock',
                        to='entreprise.entreprise',
                    ),
                ),
                (
                    'pointvente',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='entreprise.pointvente',
                    ),
                ),
            ],
            options={
                'verbose_name': "Bon d'ajustement stock",
                'verbose_name_plural': "Bons d'ajustement stock",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneBonAjustement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.SmallIntegerField(choices=[(1, 'Entrée'), (-1, 'Sortie')])),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                (
                    'bon',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lignes',
                        to='stock.bonajustementstock',
                    ),
                ),
                (
                    'mouvement_stock',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='ajustements_bon_trace',
                        to='stock.mouvementstock',
                    ),
                ),
            ],
            options={
                'verbose_name': "Ligne de bon d'ajustement",
                'verbose_name_plural': "Lignes de bon d'ajustement",
                'ordering': ['date_creation'],
            },
        ),
    ]
