# Generated by Django 5.2.12 on 2026-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_quantite_ecartee_quantite_ecarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='origine',
            field=models.CharField(choices=[('BR', 'Bon de réception'), ('AJUSTEMENT', 'Ajustement manuel'), ('INVENTAIRE', 'Inventaire (écart physique)'), ('VENTE', 'Sortie vente (facture)'), ('RETOUR_VENTE', 'Retour client (avoir)')], default='BR', max_length=20, verbose_name='Origine du mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite_ecarter',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Mis à l’écart à la réception ou par opération : augmente cette valeur → disponible active diminue (distinct de l’écart de campagne d’inventaire sur une ligne inventaire).', max_digits=15, verbose_name='Quantité à l’écart'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='sens_adjustement',
            field=models.IntegerField(blank=True, choices=[(1, 'Entrée'), (-1, 'Sortie interne')], help_text="Rempli uniquement pour les lignes d'ajustement manuel (+ entrée stock, − sortie).", null=True, verbose_name='Sens ajustement'),
        ),
    ]
