# Generated by Django 5.2.12 on 2026-05-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
        ('stock', '0010_alter_mouvementstock_origine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='origine',
            field=models.CharField(choices=[('BR', 'Bon de réception'), ('AJUSTEMENT', 'Ajustement manuel'), ('INVENTAIRE', 'Inventaire (écart physique)'), ('VENTE', 'Sortie vente (facture)'), ('RETOUR_VENTE', 'Retour client (avoir)'), ('TRANSFERT_SORTIE', 'Transfert — sortie de la source'), ('TRANSFERT_ENTREE', 'Transfert — entrée à la destination')], default='BR', max_length=20, verbose_name='Origine du mouvement'),
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('type_transfert', models.CharField(choices=[('DEPOT_PDV', 'Dépôt → Point de vente'), ('PDV_DEPOT', 'Point de vente → Dépôt'), ('DEPOT_DEPOT', 'Dépôt → Dépôt'), ('PDV_PDV', 'Point de vente → Point de vente')], max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('dest_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_dest_depot', to='entreprise.depot')),
                ('dest_pdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_dest_pdv', to='entreprise.pointvente')),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('source_depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_source_depot', to='entreprise.depot')),
                ('source_pdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferts_source_pdv', to='entreprise.pointvente')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mouvement_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_transfert_dest', to='stock.mouvementstock')),
                ('mouvement_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_transfert_source', to='stock.mouvementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.transfertstock')),
            ],
            options={
                'verbose_name': 'Ligne de transfert',
                'verbose_name_plural': 'Lignes de transfert',
            },
        ),
    ]
