# Generated by Django 5.2.12 on 2026-05-04 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
        ('stock', '0011_transfert_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transfertstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_transfert', 'DEPOT_DEPOT'), _negated=True), models.Q(('source_depot', models.F('dest_depot')), _negated=True), _connector='OR'), name='transfert_depot_depot_source_diff_dest'),
        ),
        migrations.AddConstraint(
            model_name='transfertstock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_transfert', 'PDV_PDV'), _negated=True), models.Q(('source_pdv', models.F('dest_pdv')), _negated=True), _connector='OR'), name='transfert_pdv_pdv_source_diff_dest'),
        ),
    ]
