# Generated by Django 4.0 on 2026-03-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_branche', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('est_siege_social', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_depot', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('est_principal', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='entreprise.branche')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('rccm', models.CharField(blank=True, max_length=100, verbose_name='RCCM / ID National')),
                ('adresse_siege', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='entreprise.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prix_vente_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('unite_mesure', models.CharField(choices=[('PCS', 'Pièce'), ('KG', 'Kilogramme'), ('L', 'Litre'), ('M', 'Mètre'), ('BOX', 'Carton/Boîte')], default='PCS', max_length=10)),
                ('stock_alerte', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='entreprise.souscategorie')),
            ],
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pointvente', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=255)),
                ('est_actif', models.BooleanField(default=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_de_vente', to='entreprise.branche')),
                ('depot_source', models.ForeignKey(help_text="Dépôt d'où proviennent les articles vendus", null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.depot')),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('symbole', models.CharField(max_length=5)),
                ('taux_echange', models.DecimalField(decimal_places=4, default=1.0, max_digits=15)),
                ('est_principale', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devises', to='entreprise.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='branche',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='entreprise.entreprise'),
        ),
    ]
