# Generated by Django 4.0 on 2026-03-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_profil_profil_id'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intial', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('code_fournisseur', models.CharField(max_length=255)),
                ('nom_societe', models.CharField(max_length=255)),
                ('rccm_id', models.CharField(blank=True, max_length=100, verbose_name='ID Fiscal / RCCM')),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('solde_du', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='entreprise.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='methode_gestion',
            field=models.CharField(choices=[('FIFO', 'First In First Out'), ('FEFO', 'First Expire First Out'), ('LIFO', 'Last In First Out')], default='FEFO', max_length=30),
        ),
        migrations.AddField(
            model_name='produit',
            name='vie',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='OrdreAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé au Fournisseur'), ('RECU_PARTIEL', 'Reçu Partiellement'), ('RECU_TOTAL', 'Reçu Totalement'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.profil')),
                ('depot_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.depot')),
                ('devise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.devise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.fournisseur')),
                ('pointdevente_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiale', models.CharField(max_length=4)),
                ('reference', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=10)),
                ('ramassage', models.BooleanField(default=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='entreprise.branche')),
            ],
        ),
        migrations.CreateModel(
            name='LigneOrdreAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantite_recue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dateproduction', models.DateField(blank=True, null=True)),
                ('dateexpiration', models.DateField(blank=True, null=True)),
                ('lot_batch', models.CharField(max_length=20)),
                ('unite', models.CharField(max_length=20)),
                ('reception', models.BooleanField(default=False)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sous_total_ht', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.location')),
                ('ordre_achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='entreprise.ordreachat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intial', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('code_client', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('type_client', models.CharField(choices=[('AUTRE', 'Autre type client'), ('DETAIL', 'Particulier / Détail'), ('GROS', 'Grossiste / Entreprise')], default='DETAIL', max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('solde_compte', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('points_fidelite', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='entreprise.branche')),
            ],
        ),
    ]
