# Generated by Django 5.2.12 on 2026-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_entreprise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branche',
            name='init_bdcommande',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branche',
            name='init_facture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branche',
            name='init_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branche',
            name='init_proforma',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
