# Generated by Django 5.2.12 on 2026-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_branche_init_bdcommande_branche_init_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='idnat',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID National'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='rccm',
            field=models.CharField(blank=True, max_length=100, verbose_name='RCCM '),
        ),
    ]
