# Generated by Django 5.2.12 on 2026-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_entreprise_idnat_alter_entreprise_rccm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='numero_impot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero Impôt'),
        ),
    ]
