# Generated by Django 5.2.12 on 2026-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_entreprise_numero_impot'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='nepas_actif',
            field=models.BooleanField(default=False),
        ),
    ]
