# Generated by Django 5.2.12 on 2026-03-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_entreprise_nepas_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='branche',
            name='sans_etagere_ordonne',
            field=models.BooleanField(default=False),
        ),
    ]
