# Generated by Django 5.2.12 on 2026-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_branche_sans_etagere_ordonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
    ]
