# Generated by Django 5.2.12 on 2026-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0010_alter_entreprise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branche',
            name='code_branche',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
