# Generated by Django 5.2.12 on 2026-04-10 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0011_alter_branche_code_branche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='location',
            name='capacite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='entreprise.branche'),
        ),
    ]
