# Generated by Django 5.2.12 on 2026-04-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0012_alter_location_options_location_capacite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterField(
            model_name='depot',
            name='code_depot',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
