# Generated by Django 5.2.12 on 2026-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0013_alter_location_options_alter_depot_code_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
