# Generated by Django 5.2.12 on 2026-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0014_alter_depot_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='code_depot',
            field=models.CharField(error_messages='Une autre dépôt existe déjà', max_length=5, unique=True),
        ),
    ]
