# Generated by Django 5.2.12 on 2026-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0015_alter_depot_code_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='code_depot',
            field=models.CharField(error_messages={'unique': 'Un autre dépôt existe déjà avec ce code.'}, max_length=5, unique=True),
        ),
    ]
