# Generated by Django 5.2.12 on 2026-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0016_alter_depot_code_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvente',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pointvente',
            name='code_pointvente',
            field=models.CharField(error_messages={'unique': 'Un autre dépôt existe déjà avec ce code.'}, max_length=5, unique=True),
        ),
    ]
