# Generated by Django 5.2.12 on 2026-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0017_pointvente_adresse_alter_pointvente_code_pointvente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointvente',
            name='code_pointvente',
            field=models.CharField(error_messages={'unique': 'Un autre point de vente existe déjà avec ce code.'}, max_length=5, unique=True),
        ),
    ]
