# Generated by Django 5.2.12 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entreprise", "0018_alter_pointvente_code_pointvente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fournisseur",
            name="intial",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="reference",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="fournisseur",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "code_fournisseur"),
                name="uniq_fournisseur_code_par_entreprise",
            ),
        ),
    ]

