# Generated by Django 5.2.12 on 2026-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0019_fournisseur_code_unique_and_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depot',
            options={'verbose_name': 'Dépôt', 'verbose_name_plural': 'Dépôts'},
        ),
        migrations.AlterModelOptions(
            name='pointvente',
            options={'verbose_name': 'Point de vente', 'verbose_name_plural': 'Points de vente'},
        ),
        migrations.AlterField(
            model_name='depot',
            name='code_depot',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pointvente',
            name='code_pointvente',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='depot',
            unique_together={('branche', 'code_depot')},
        ),
        migrations.AlterUniqueTogether(
            name='pointvente',
            unique_together={('branche', 'code_pointvente')},
        ),
    ]
