# Generated by Django 5.2.12 on 2026-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0022_remove_ordreachat_ligneordreachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Référence interne / unité de stock (unique par sous-catégorie si renseignée).', max_length=100, verbose_name='SKU'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sous_categorie', 'sku'), name='uniq_produit_sku_par_sous_categorie'),
        ),
    ]
