# Generated by Django 5.2.12 on 2026-04-28 20:44

from django.db import migrations, models


def _normalize_and_dedupe_sku(apps, schema_editor):
    """Vide SKU → NULL ; un seul produit conserve un SKU donné par sous-catégorie."""
    Produit = apps.get_model('entreprise', 'Produit')
    Produit.objects.filter(sku='').update(sku=None)
    for p in Produit.objects.exclude(sku__isnull=True).only('id', 'sku'):
        if not (p.sku or '').strip():
            Produit.objects.filter(pk=p.pk).update(sku=None)

    seen = set()
    for p in (
        Produit.objects.exclude(sku__isnull=True)
        .order_by('sous_categorie_id', 'sku', 'id')
        .only('id', 'sous_categorie_id', 'sku')
    ):
        key = (p.sous_categorie_id, p.sku)
        if key in seen:
            Produit.objects.filter(pk=p.pk).update(sku=None)
        else:
            seen.add(key)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0023_produit_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produit',
            name='uniq_produit_sku_par_sous_categorie',
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Référence interne / unité de stock (unique par sous-catégorie si renseignée).', max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.RunPython(_normalize_and_dedupe_sku, _noop_reverse),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('sous_categorie', 'sku'), name='uniq_produit_sku_par_sous_categorie'),
        ),
    ]
