# Generated by Django 5.2.12 on 2026-05-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0025_produit_entreprise_sku_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(help_text='Renseigné automatiquement selon la sous-catégorie ; sert à l’unicité du SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='entreprise.entreprise', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Référence interne / unité de stock (unique par entreprise si renseignée).', max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
