"""URLs application stock — dépôt / point de vente séparés, périmètre entreprise."""

from django.urls import path
from django.views.generic import RedirectView

from . import export_views
from . import views

app_name = 'stock'

urlpatterns = [
    path('', views.hub_stock, name='hub-stock'),
    path(
        'liste/',
        RedirectView.as_view(pattern_name='stock:hub-stock', permanent=False),
        name='liste-stock',
    ),
    path(
        'depots/export/excel/',
        export_views.export_liste_stock_depot_excel,
        name='export-stock-depot-excel',
    ),
    path(
        'depots/export/pdf/',
        export_views.export_liste_stock_depot_pdf,
        name='export-stock-depot-pdf',
    ),
    path(
        'depots/synthese-produits/export/excel/',
        export_views.export_synthese_depot_excel,
        name='export-synthese-depot-excel',
    ),
    path(
        'depots/synthese-produits/export/pdf/',
        export_views.export_synthese_depot_pdf,
        name='export-synthese-depot-pdf',
    ),
    path(
        'depots/mise-a-ecart/export/excel/',
        export_views.export_mise_a_ecart_depot_excel,
        name='export-mise-a-ecart-depot-excel',
    ),
    path(
        'depots/mise-a-ecart/export/pdf/',
        export_views.export_mise_a_ecart_depot_pdf,
        name='export-mise-a-ecart-depot-pdf',
    ),
    path(
        'points-vente/export/excel/',
        export_views.export_liste_stock_pdv_excel,
        name='export-stock-pdv-excel',
    ),
    path(
        'points-vente/export/pdf/',
        export_views.export_liste_stock_pdv_pdf,
        name='export-stock-pdv-pdf',
    ),
    path(
        'points-vente/synthese-produits/export/excel/',
        export_views.export_synthese_pdv_excel,
        name='export-synthese-pdv-excel',
    ),
    path(
        'points-vente/synthese-produits/export/pdf/',
        export_views.export_synthese_pdv_pdf,
        name='export-synthese-pdv-pdf',
    ),
    path(
        'points-vente/mise-a-ecart/export/excel/',
        export_views.export_mise_a_ecart_pdv_excel,
        name='export-mise-a-ecart-pdv-excel',
    ),
    path(
        'points-vente/mise-a-ecart/export/pdf/',
        export_views.export_mise_a_ecart_pdv_pdf,
        name='export-mise-a-ecart-pdv-pdf',
    ),
    path(
        'mouvements/depots/export/excel/',
        export_views.export_mouvements_depot_excel,
        name='export-mouvements-depot-excel',
    ),
    path(
        'mouvements/depots/export/pdf/',
        export_views.export_mouvements_depot_pdf,
        name='export-mouvements-depot-pdf',
    ),
    path(
        'mouvements/points-vente/export/excel/',
        export_views.export_mouvements_pdv_excel,
        name='export-mouvements-pdv-excel',
    ),
    path(
        'mouvements/points-vente/export/pdf/',
        export_views.export_mouvements_pdv_pdf,
        name='export-mouvements-pdv-pdf',
    ),
    path(
        'produit/<int:pk>/export/excel/',
        export_views.export_produit_stock_excel,
        name='export-produit-stock-excel',
    ),
    path(
        'produit/<int:pk>/export/pdf/',
        export_views.export_produit_stock_pdf,
        name='export-produit-stock-pdf',
    ),
    path(
        'inventaires/export/excel/',
        export_views.export_inventaires_liste_excel,
        name='export-inventaires-liste-excel',
    ),
    path(
        'inventaires/export/pdf/',
        export_views.export_inventaires_liste_pdf,
        name='export-inventaires-liste-pdf',
    ),
    path(
        'inventaires/<int:pk>/export/excel/',
        export_views.export_inventaire_detail_excel,
        name='export-inventaire-detail-excel',
    ),
    path(
        'inventaires/<int:pk>/export/pdf/',
        export_views.export_inventaire_detail_pdf,
        name='export-inventaire-detail-pdf',
    ),
    path('depots/', views.liste_stocks_depot, name='liste-stock-depot'),
    path(
        'depots/synthese-produits/',
        views.liste_stocks_depot_synthese,
        name='liste-stock-depot-synthese',
    ),
    path(
        'depots/mise-a-ecart/lignes-picker/',
        views.mise_ecart_lignes_picker_depot,
        name='mise-ecart-lignes-picker-depot',
    ),
    path(
        'depots/mise-a-ecart/',
        views.mise_a_ecart_depot,
        name='mise-a-ecart-depot',
    ),
    path('points-vente/', views.liste_stocks_pdv, name='liste-stock-pdv'),
    path(
        'points-vente/synthese-produits/',
        views.liste_stocks_pdv_synthese,
        name='liste-stock-pdv-synthese',
    ),
    path(
        'points-vente/mise-a-ecart/lignes-picker/',
        views.mise_ecart_lignes_picker_pdv,
        name='mise-ecart-lignes-picker-pdv',
    ),
    path(
        'points-vente/mise-a-ecart/',
        views.mise_a_ecart_pdv,
        name='mise-a-ecart-pdv',
    ),
    path(
        'mise-a-ecart/<int:pk>/retirer/',
        views.mise_a_ecart_retirer,
        name='mise-a-ecart-retirer',
    ),
    path('mouvements/depots/', views.liste_mouvements_depot, name='liste-mouvements-depot'),
    path(
        'mouvements/points-vente/',
        views.liste_mouvements_pdv,
        name='liste-mouvements-pdv',
    ),
    path(
        'mouvements/',
        RedirectView.as_view(pattern_name='stock:hub-stock', permanent=False),
        name='liste-mouvements',
    ),
    path('produit/<int:pk>/', views.detail_produit_stock, name='detail-produit-stock'),
    path(
        'ajuster/depot/lignes-picker/',
        views.ajuster_lignes_picker_depot,
        name='ajuster-lignes-picker-depot',
    ),
    path(
        'ajuster/point-de-vente/lignes-picker/',
        views.ajuster_lignes_picker_pdv,
        name='ajuster-lignes-picker-pdv',
    ),
    path('ajuster/depot/', views.ajuster_stock_depot, name='ajuster-stock-depot'),
    path(
        'ajuster/point-de-vente/',
        views.ajuster_stock_pdv,
        name='ajuster-stock-pdv',
    ),
    path(
        'bons-ajustement/depots/',
        views.liste_bons_ajustement_depot,
        name='liste-bons-ajustement-depot',
    ),
    path(
        'bons-ajustement/points-vente/',
        views.liste_bons_ajustement_pdv,
        name='liste-bons-ajustement-pdv',
    ),
    path(
        'bons-ajustement/<int:pk>/',
        views.detail_bon_ajustement,
        name='detail-bon-ajustement',
    ),
    path(
        'ajuster/',
        RedirectView.as_view(pattern_name='stock:hub-stock', permanent=False),
        name='ajuster-stock',
    ),
    path(
        'correction-interne/depots/lignes-picker/',
        views.correction_lignes_picker_depot,
        name='correction-interne-lignes-picker-depot',
    ),
    path(
        'correction-interne/points-vente/lignes-picker/',
        views.correction_lignes_picker_pdv,
        name='correction-interne-lignes-picker-pdv',
    ),
    path(
        'correction-interne/depots/',
        views.correction_interne_depot,
        name='correction-interne-depot',
    ),
    path(
        'correction-interne/points-vente/',
        views.correction_interne_pdv,
        name='correction-interne-pdv',
    ),
    path('inventaires/', views.liste_inventaires, name='liste-inventaires'),
    path(
        'inventaires/depots/creer/',
        views.creer_inventaire_depot,
        name='creer-inventaire-depot',
    ),
    path(
        'inventaires/points-vente/creer/',
        views.creer_inventaire_pdv,
        name='creer-inventaire-pdv',
    ),
    path(
        'inventaires/creer/',
        RedirectView.as_view(pattern_name='stock:liste-inventaires', permanent=False),
        name='creer-inventaire',
    ),
    path('inventaires/<int:pk>/', views.detail_inventaire, name='detail-inventaire'),
    path(
        'inventaires/<int:pk>/lignes/import-excel/',
        views.inventaire_import_excel_lignes,
        name='inventaire-import-excel-lignes',
    ),
    path(
        'inventaires/<int:pk>/lignes/modele-excel/',
        views.inventaire_modele_import_excel,
        name='inventaire-modele-import-lignes',
    ),
    path(
        'inventaires/<int:pk>/lignes/',
        views.inventaire_ajouter_ligne,
        name='inventaire-ajouter-ligne',
    ),
    path(
        'inventaires/<int:pk>/lignes/<int:ligne_pk>/supprimer/',
        views.inventaire_supprimer_ligne,
        name='inventaire-supprimer-ligne',
    ),
    path(
        'inventaires/<int:pk>/cloturer/',
        views.inventaire_cloturer,
        name='inventaire-cloturer',
    ),
]
