# Generated by Django 4.0 on 2026-03-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0002_fournisseur_produit_methode_gestion_produit_vie_and_more'),
        ('utilisateur', '0002_profil_profil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('classe', models.CharField(choices=[('1', 'Comptes de capitaux'), ('2', "Comptes d'immobilisations"), ('3', 'Comptes de stocks'), ('4', 'Comptes de tiers'), ('5', 'Comptes de trésorerie'), ('6', 'Comptes de charges'), ('7', 'Comptes de produits'), ('8', 'Comptes spéciaux')], max_length=1)),
                ('est_actif', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.comptecomptable')),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_piece', models.CharField(max_length=50)),
                ('date_comptable', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('VENTE', 'Journal des Ventes'), ('ACHAT', 'Journal des Achats'), ('CAISSE', 'Journal de Caisse'), ('BANQUE', 'Journal de Banque'), ('OD', 'Opérations Diverses')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finance.ecriturecomptable')),
            ],
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal'),
        ),
    ]
