# Generated by Django 4.0 on 2026-03-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0002_profil_profil_id'),
        ('entreprise', '0002_fournisseur_produit_methode_gestion_produit_vie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('etat_civil', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié'), ('D', 'Divorcé'), ('V', 'Veuf')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rh/employes/')),
                ('est_actif', models.BooleanField(default=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.branche')),
                ('user_compte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilisateur.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(null=True)),
                ('heure_depart', models.TimeField(null=True)),
                ('statut', models.CharField(default='PRESENT', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirige_departement', to='rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Durable'), ('CDD', 'Durée Déterminée'), ('STAGE', 'Stage')], max_length=10)),
                ('titre_poste', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('est_actuel', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.departement')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Annuel'), ('MALADIE', 'Maladie'), ('MATERNITE', 'Maternité')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('approuve', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mois', models.IntegerField()),
                ('periode_annee', models.IntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('est_paye', models.BooleanField(default=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.employe')),
            ],
        ),
    ]
