# Generated by Django 4.0 on 2026-03-07 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
