# Generated by Django 5.2.12 on 2026-03-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_profil_profil_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
