# Generated by Django 5.2.12 on 2026-04-27 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0019_fournisseur_code_unique_and_defaults'),
        ('utilisateur', '0003_profil_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionpersonnalisee',
            options={'verbose_name': 'Permission personnalisée', 'verbose_name_plural': 'Permissions personnalisées'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rôle'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Permission du rôle', 'verbose_name_plural': 'Permissions des rôles'},
        ),
        migrations.AddField(
            model_name='profil',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='derniere_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='branche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='entreprise.branche'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='utilisateur.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entreprise.entreprise'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='utilisateur.permissionpersonnalisee'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('entreprise', 'nom')},
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tente', models.CharField(blank=True, max_length=254)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('succes', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journal des connexions',
                'ordering': ['-date_heure'],
            },
        ),
    ]
