# Generated by Django 5.2.12 on 2026-04-27 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_permissionpersonnalisee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature utilisée sur les documents (factures, bons de commande…)', null=True, upload_to='signatures/'),
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbe', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('module', models.CharField(blank=True, help_text='ex : utilisateurs, facturation, stock', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date_heure'],
            },
        ),
    ]
