# Generated by Django 5.2.12 on 2026-04-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0019_fournisseur_code_unique_and_defaults'),
        ('utilisateur', '0005_profil_signature_journalaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_voir', models.BooleanField(default=True, verbose_name='Voir le stock')),
                ('peut_recevoir', models.BooleanField(default=False, verbose_name='Réceptionner des marchandises')),
                ('peut_expedier', models.BooleanField(default=False, verbose_name='Expédier / Transférer')),
                ('peut_inventorier', models.BooleanField(default=False, verbose_name='Faire un inventaire')),
                ('peut_administrer', models.BooleanField(default=False, verbose_name='Administrer le dépôt')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_utilisateurs', to='entreprise.depot')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_depots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès dépôt',
                'verbose_name_plural': 'Accès dépôts',
                'unique_together': {('utilisateur', 'depot')},
            },
        ),
        migrations.CreateModel(
            name='AccesPointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_voir', models.BooleanField(default=True, verbose_name='Voir le point de vente')),
                ('peut_vendre', models.BooleanField(default=False, verbose_name='Créer des ventes')),
                ('peut_faire_avoir', models.BooleanField(default=False, verbose_name='Émettre des avoirs')),
                ('peut_remise', models.BooleanField(default=False, verbose_name='Accorder des remises')),
                ('peut_gerer_caisse', models.BooleanField(default=False, verbose_name='Gérer la caisse')),
                ('peut_administrer', models.BooleanField(default=False, verbose_name='Administrer le point de vente')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_utilisateurs', to='entreprise.pointvente')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_points_vente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès point de vente',
                'verbose_name_plural': 'Accès points de vente',
                'unique_together': {('utilisateur', 'point_vente')},
            },
        ),
    ]
