# Generated by Django 5.2.12 on 2026-05-04 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depenses', '0001_initial'),
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
        ('facturation', '0007_retourvente_approbation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_ATTENTE_CLOTURE', 'En attente de clôture'), ('CLOSE', 'Clôturée'), ('REJETEE', 'Clôture rejetée')], default='OUVERTE', max_length=25)),
                ('date_ouverture', models.DateTimeField(default=django.utils.timezone.now)),
                ('fond_reel_cloture', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('commentaire_cloture', models.TextField(blank=True, default='')),
                ('soumis_cloture_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire_manager', models.TextField(blank=True, default='')),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_approuvees', to=settings.AUTH_USER_MODEL)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_ouvertes', to=settings.AUTH_USER_MODEL)),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='entreprise.pointvente')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('type_transaction', models.CharField(choices=[('ENCAISSEMENT', 'Encaissement'), ('DECAISSEMENT', 'Décaissement'), ('DEPOT', 'Dépôt de fonds'), ('RETRAIT', 'Retrait de fonds')], max_length=20)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('CREDIT', 'Crédit client'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_echange', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_caisse', to='depenses.depense')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_caisse', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_caisse', to='facturation.facture')),
                ('retour_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_caisse', to='facturation.retourvente')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='caisse.sessioncaisse')),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'verbose_name_plural': 'Transactions de caisse',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
