# Generated by Django 5.2.12 on 2026-05-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_session_transaction'),
        ('tiers', '0005_alter_client_est_client_passager'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncaisse',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_caisse', to='tiers.client'),
        ),
    ]
