# Generated by Django 4.0 on 2026-03-08 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0002_fournisseur_produit_methode_gestion_produit_vie_and_more'),
        ('stock', '0001_initial'),
        ('utilisateur', '0002_profil_profil_id'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=50, unique=True)),
                ('taux_echange_appliqué', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mode_paiement', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte Bancaire'), ('CREDIT', 'Crédit / À terme')], default='CASH', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='tiers.client')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.pointvente')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateur.profil')),
            ],
        ),
        migrations.CreateModel(
            name='FactureProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proforma', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_validite', models.DateField(help_text="Date limite de validité de l'offre")),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée / Convertie'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.branche')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.client')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('facture_definitive', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.facture')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateur.profil')),
            ],
        ),
        migrations.CreateModel(
            name='LigneProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sous_total_ttc', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.produit')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.factureproforma')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sous_total_ttc', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='entreprise.produit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.mouvementstock')),
            ],
        ),
    ]
