# Generated by Django 5.2.12 on 2026-05-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0026_alter_produit_entreprise_alter_produit_sku'),
        ('facturation', '0005_factureproforma_statut_brouillon'),
        ('stock', '0010_alter_mouvementstock_origine_and_more'),
        ('tiers', '0005_alter_client_est_client_passager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_CAISSE', 'En attente caisse'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='factureproforma',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', "En attente d'approbation"), ('ACCEPTEE', 'Acceptée / Convertie'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='RetourVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_retour', models.CharField(editable=False, max_length=50, unique=True)),
                ('taux_echange', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.client')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.devise')),
                ('facture_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='facturation.facture')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.pointvente')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_saisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tva_montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sous_total_ttc', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('ligne_facture_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='facturation.lignefacture')),
                ('mouvement_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='stock.mouvementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entreprise.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.retourvente')),
            ],
        ),
    ]
