# Generated by Django 5.2.12 on 2026-05-04 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_alter_facture_statut_alter_factureproforma_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retourvente',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_approuves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retourvente',
            name='commentaire_manager',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='retourvente',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retourvente',
            name='soumis_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retourvente',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', "En attente d'approbation"), ('APPROUVE', 'Approuvé — stock réintégré'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20),
        ),
    ]
