# Generated by Django 5.2.12 on 2026-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_client_est_client_passager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='est_client_passager',
            field=models.BooleanField(default=False, help_text='Client occasionnel enregistré rapidement lors d’un achat, à distinguer d’un client suivi régulièrement.', verbose_name='Client passager / comptoir'),
        ),
    ]
